In [6]:
a=[1.0,2.0,1.0]
print(a[0])
print(a[2])

a[2]=3.0
print(a)

1.0
1.0
[1.0, 2.0, 3.0]


In [7]:
import torch #토치 모듈 임포트
a=torch.ones(3) # 크기가 3인 1차원 텐서 만들고 값을 1로 채우기
a

tensor([1., 1., 1.])

In [12]:
print(a[1])
print(float(a[1]))
print(a[2])

tensor(1.)
1.0
tensor(1.)


In [14]:
points= torch.zeros(6) #제로를 써서 쉽게 원하는 크기의 배열을 얻음
points[0]=4.0
points[1]=1.0
points[2]=5.0
points[3]=3.0
points[4]=2.0
points[5]=1.0

points2=torch.tensor([4.0,1.0,5.0,3.0,2.0,1.0]) #생성자에 파이썬 리스트를 넘겨도댐
points2 

tensor([4., 1., 5., 3., 2., 1.])

In [16]:
float(points[0]),float(points[1])

(4.0, 1.0)

In [17]:
points=torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [20]:
points.shape

torch.Size([3, 2])

In [21]:
points=torch.zeros(3,2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [22]:
points=torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [23]:
points[0,1]

tensor(1.)

In [24]:
points[0]

tensor([4., 1.])

In [25]:
some_list=list(range(6))
some_list[:]
some_list[1:4]
some_list[:4]
some_list[:-1]
some_list[1:4:2]

points[1:] #첫번쨰 이후 모든 행에 대해 암묵적으로 모든 열이 포함됨
points[1:,:] #첫번쨰 이후 모든 행에 대해, 명시적으로 모든 열이 포함됨
points[1:,0] #첫번째 이후 모든 행에 대해 첫번쨰 열만 포함됨
points[None] #길이가 1인 차원을 추가함

[1, 3]

In [27]:
points[1:,:]

tensor([[5., 3.],
        [2., 1.]])

In [30]:
img_t=torch.randn(3,5,5) #[채널 크기, 행 크기, 열크기]
weights=torch.tensor([0.2126,0.7152,0.722])

batch_t=torch.randn(2,3,5,5) #[배치크기,채널 크기, 행 크기, 열크기]

img_gray_naive=img_t.mean(-3)
batch_gray_naive=batch_t.mean(-3)
img_gray_naive.shape,batch_gray_naive.shape


(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [31]:
unsqueezed_weights=weights.unsqueeze(-1).unsqueeze(-1)

img_weights=(img_t*unsqueezed_weights)
batch_weights=(batch_t*unsqueezed_weights)
img_gray_weighted=img_weights.sum(-3)
batch_gray_weighted=batch_weights.sum(-3)
batch_weights.shape,batch_t.shape,unsqueezed_weights.shape


(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [32]:
weights_named=torch.tensor([0.2126,0.7152,0.0722],names=['channels'])
weights_named

<ipython-input-32-088eab111a3f>:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at C:\cb\pytorch_1000000000000\work\c10/core/TensorImpl.h:1761.)
  weights_named=torch.tensor([0.2126,0.7152,0.0722],names=['channels'])


tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [33]:
img_named=img_t.refine_names(...,'channels','rows','columns')
batch_named=batch_t.refine_names(...,'channels','rows','columns')
print("img_named:",img_named.shape,img_named.names)
print("batch named:",batch_named.shape,batch_named.names)

img_named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch named: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


In [36]:
weights_aligned=weights_named.align_as(img_named)
weights_aligned.shape,weightes_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

In [37]:
gray_named=(img_named*weights_aligned).sum('channels')
gray_named.shape,gray_named.names

(torch.Size([5, 5]), ('rows', 'columns'))

In [39]:
gray_plain=gray_named.rename(None)
gray_plain.shape,gray_plain.names

(torch.Size([5, 5]), (None, None))

In [43]:
double_points=torch.ones(10,2,dtype=torch.double)
short_points=torch.tensor([[1,2],[3,4]],dtype=torch.short)

short_points.dtype

torch.int16

In [44]:
double_points=torch.zeros(10,2).double()
short_points=torch.ones(10,2).short()

double_points=torch.zeros(10,2).to(torch.double())
short_points=torch.ones(10,2).to(torch.short())


TypeError: 'torch.dtype' object is not callable

In [45]:
points_64=torch.rand(5,dtype=torch.double)
points_short=points_64.to(torch.short)
points_64*points_short

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

In [46]:
a=torch.ones(3,2)
a_t=torch.transpose(a,0,1)
a.shape,a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [49]:
a_b=torch.transpose(a)
a_b.shape

TypeError: transpose() received an invalid combination of arguments - got (Tensor), but expected one of:
 * (Tensor input, int dim0, int dim1)
 * (Tensor input, name dim0, name dim1)


In [50]:
a=torch.ones(3,2)
a_t=a.transpose(0,1)

a.shape,a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [4]:
points=torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points.storage

<bound method Tensor.storage of tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])>

In [5]:
points_storage=points.storage()
points_storage[0]

4.0

In [3]:
import torch

In [6]:
points.storage()[1]

1.0

In [7]:
points=torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points_storage=points.storage()
points_storage[0]=2.0
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [8]:
a=torch.ones(3,2)
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [17]:
points=torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
second_point=points[1]
second_point

tensor([5., 3.])

In [18]:
second_point.storage_offset()

2

In [19]:
second_point.size()

torch.Size([2])

In [20]:
pointss=torch.tensor([[4.0,1.0,41.0],[5.0,3.0,53.0],[2.0,1.0,21.0]])
seconds_point=pointss[1]
seconds_point

tensor([ 5.,  3., 53.])

In [21]:
seconds_point.storage_offset()

3

In [22]:
seconds_point.size()

torch.Size([3])

In [23]:
points.stride()

(2, 1)

In [24]:
pointss.stride()

(3, 1)

In [70]:
second_tensor=torch.tensor([[1,5],[2,7],[9,3]])
y=second_tensor[2]
y.storage_offset()

4

In [72]:
y.size()

torch.Size([2])

In [61]:
t=second_tensor[0]
t

tensor([1, 5])

In [62]:
t.storage_offset()

0

In [58]:
t.stride()

(1,)

In [54]:
s=second_tensor[1]
s

tensor([3, 4])

In [55]:
s.storage_offset()

2

In [59]:
s.stride()

(1,)

In [56]:
k=second_tensor[2]
k

tensor([5, 6])

In [57]:
k.storage_offset()

4

k=second_tensor[2]
k

In [36]:
second_tensor.stride()[0]

2

In [30]:
second_tensor.storage_offset() + second_tensor.stride()[0] + i +second_tensor.stride()[1] + j

10

In [31]:
second_tensor.stride()[1]

1

In [77]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
y_point=points[1].clone()
y_point[0]=10.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [78]:
y_point

tensor([10.,  3.])

In [83]:
tt=torch.tensor([[4,3],[2,1]])
tt

tensor([[4, 3],
        [2, 1]])

In [84]:
tt_t=tt.t()
tt_t

tensor([[4, 2],
        [3, 1]])

In [89]:
tt_p=torch.permute(tt,(2,1))
tt_p

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

In [90]:
id(tt.storage()) == id(tt_t.storage())

True

In [93]:
some_t=torch.ones(3,4,5) #3차원 4,5 배열
tranpose_t=some_t.transpose(0,2) #바꿔줄 자릿수 
some_t.shape


torch.Size([3, 4, 5])

In [94]:
tranpose_t.shape


torch.Size([5, 4, 3])

In [97]:
points=torch.tensor([[1,2],[3,4],[5,6]])
points_t= points.t()
points_t

tensor([[1, 3, 5],
        [2, 4, 6]])

In [98]:
print(points.stride())
print(points_t.stride())

(2, 1)
(1, 2)


In [99]:
points_t_cont=points_t.contiguous()
points_t_cont

tensor([[1, 3, 5],
        [2, 4, 6]])

In [101]:
print(points_t_cont.stride())
print(points_t_cont.storage())

(3, 1)
 1
 3
 5
 2
 4
 6
[torch.storage.TypedStorage(dtype=torch.int64, device=cpu) of size 6]


In [103]:
points_gpu=torch.tensor([[4,1],[5,3],[2,1]],device='cuda')

AssertionError: Torch not compiled with CUDA enabled

In [104]:
print(torch.cuda.is_available())

False


In [105]:
import torch

print(torch.__version__)
my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32, device="cpu")
print(my_tensor)
torch.cuda.is_available()

1.13.1
tensor([[1., 2., 3.],
        [4., 5., 6.]])


False